import React, { Component } from 'react';
import '../styles/About.css';
import aboutImage1 from '../images/islandgif1.GIF';
import aboutImage2 from '../images/islandgif2.GIF';
import cloudImage from '../images/cloud2.png'

class About extends Component {
    render() {
        return (
            <div id="about" className="About container site-section">
                <div className="row">
                    <div className="col-md-6 col-sm-12">
                        <h1 className="About-section-header">
                            What is HackReality?
                        </h1>
                        <div className="About-text-content">
                            <p>
                            HackReality is the first student-led XR themed hackathon from UNC-Chapel Hill. We are dedicated in introducing XR in a fun, accessible and creative way to the community by connecting attendees with leading researchers, professionals and XR enthusiasts in the field.                        </p>
                            <p>
                            Come join us and learn about this emerging technology and play a part in defining the future! Attend workshops, network with companies and peers, and conquer challenges with the help of experienced mentors. Create impactful projects, win cool prizes and create lasting memories with us here at Hack Reality!
                        </p>
                        </div>
                    </div>
                    <div className="col-md-6 col-sm-12 center-img-container">
                        <img
                            className="About-island"
                            src={aboutImage1}
                            alt=""
                        />
                    </div>
                </div>
                <div className="row" id="about-xr">
                    <div className="col-md-6 col-sm-12 order-md-2">
                        <h1 className="About-section-header">
                            What is XR?
                        </h1>
                        <div className="About-text-content">
                            <p>
                                <span>XR</span> stands for Extended Reality,
                            and is an umbrella term for both AR and VR. XR refers to all real
                            and virtual environments generated by computer graphics and
                            wearables.
                        </p>
                            <p>
                                <span>VR</span> or Virtual Reality, uses either
                            VR headsets or multi-projected environments to generate realistic
                            vision, sound and other sensations that simulate users' physical
                            presence in a virtual environment. Ready Player One, The Matrix and
                            Beat Saber are all examples of Virtual Reality.
                        </p>
                            <p>
                                <span>AR</span> meaning Augmented Reality, is
                            an overlay of computer-generated content on the real world that can
                            superficially interact with the environment in real time. PokemonGo,
                            SnapChat Face Filters and Google Translate AR are all examples of
                            Augmented Reality.
                        </p>
                        </div>

                    </div>
                    <div className="col-md-6 col-sm-12 center-img-container order-md-1">
                        <img
                            className="About-island"
                            src={aboutImage2}
                            alt=""
                        />
                    </div>
                </div>
                <div className="row">
                    <div className="col-md-6 col-sm-12">
                        <img
                            className="About-cloud"
                            src={cloudImage}
                            alt=""
                        />
                    </div>
                    <div className="col-md-6 col-sm-12"></div>
                </div>
            </div>
        );
    }
}
export default About;